import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Raleway, Outfit } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import ReduxProvider from "@/redux/Provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from 'sonner'
import { ThemeProvider } from "next-themes";

const outfitHeading = Outfit({ subsets: ['latin'], variable: '--font-heading' });

const raleway = Raleway({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html
    //   lang="en"
    //   className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", raleway.variable, outfitHeading.variable)}>
    //   <body className={`${geistSans.variable} ${geistMono.variable}`}>
    //     <Toaster />
    //     <ReduxProvider>
    //       <TooltipProvider>
    //         <ThemeProvider attribute="class">
    //           {children}
    //         </ThemeProvider>
    //       </TooltipProvider>
    //     </ReduxProvider>
    //   </body>
    // </html>
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        raleway.variable,
        outfitHeading.variable
      )}
    >
      <body className={`${geistSans.variable} ${geistMono.variable}`}>

        <ReduxProvider>
          <TooltipProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
              <Toaster />
            </ThemeProvider>
          </TooltipProvider>
        </ReduxProvider>

      </body>
    </html>
  );
}
