import { IconType } from "react-icons"
import { FaCode, FaReact, FaNodeJs, FaPython, FaDocker, FaAws, FaGithub, FaGitAlt, FaCss3Alt, FaHtml5, FaJava, FaJsSquare, FaJs } from "react-icons/fa"
import { TbBrandReactNative, TbBrandReact } from "react-icons/tb"
import {
    SiNextdotjs, SiTypescript, SiJavascript, SiExpress, SiMongodb, SiPostgresql,
    SiRedis, SiGraphql, SiRedux, SiTailwindcss, SiPrisma, SiDjango, SiFlask,
    SiFigma, SiVuedotjs, SiAngular, SiBootstrap, SiSass, SiMysql, SiFirebase,
    SiJest, SiEslint, SiPrettier, SiWebpack, SiVite, SiMui, SiRust, SiGo,
    SiNestjs, SiKubernetes, SiGooglecloud, SiGitlab, SiGithubactions,
    SiApollographql,     SiCss, SiHtml5, SiLinux, SiFramer, SiPostman, SiSwagger,
    SiSocketdotio, SiJquery, SiPhp, SiLaravel, SiKotlin, SiSwift, SiFlutter,
    SiDart, SiRubyonrails, SiRuby, SiGradle, SiNpm, SiYarn, SiPnpm, SiBun,
    SiTurborepo, SiStorybook, SiCypress,
} from "react-icons/si"

export const iconMap: Record<string, IconType> = {
    FaCode,
    FaReact,
    FaNodeJs,
    FaPython,
    FaDocker,
    FaAws,
    FaGithub,
    FaGitAlt,
    FaCss3Alt,
    FaHtml5,
    FaJava,
    FaJsSquare,
    FaJs,
    TbBrandReactNative,
    TbBrandReact,
    SiNextdotjs,
    SiTypescript,
    SiJavascript,
    SiExpress,
    SiMongodb,
    SiPostgresql,
    SiRedis,
    SiGraphql,
    SiRedux,
    SiTailwindcss,
    SiPrisma,
    SiDjango,
    SiFlask,
    SiFigma,
    SiVuedotjs,
    SiAngular,
    SiBootstrap,
    SiSass,
    SiMysql,
    SiFirebase,
    SiJest,
    SiEslint,
    SiPrettier,
    SiWebpack,
    SiVite,
    SiMui,
    SiRust,
    SiGo,
    SiNestjs,
    SiKubernetes,
    SiGooglecloud,
    SiGitlab,
    SiGithubactions,
    SiApollographql,
    SiCss,
    SiHtml5,
    SiLinux,
    SiFramer,
    SiPostman,
    SiSwagger,
    SiSocketdotio,
    SiJquery,
    SiPhp,
    SiLaravel,
    SiKotlin,
    SiSwift,
    SiFlutter,
    SiDart,
    SiRubyonrails,
    SiRuby,
    SiGradle,
    SiNpm,
    SiYarn,
    SiPnpm,
    SiBun,
    SiTurborepo,
    SiStorybook,
    SiCypress,
}

export function getIcon(name: string | null, fallback: IconType = FaCode): IconType {
    if (!name) return fallback
    const trimmed = name.trim()
    return iconMap[trimmed] ?? fallback
}
